name: 'Upload to Google Drive'
description: 'Uploads a file or a folder to Google Drive'
author: 'Hackoak'
inputs: 
  credentials:
    description: 'Google Service Account credentials as encoded as base64 string'
    required: true
  folder:
    description: 'Google Drive folder ID to upload the file/folder to'
    required: true
  target:
    description: 'Local path to the file/folder to upload'
    required: true
  name:
    description: 'Optional name for the zipped file'
    required: false
    default: null
outputs:
  link:
    description: 'A link to the Drive folder'
runs:
  using: 'node12'
  main: 'dist/main.js'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
